// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5xxGLmrqXDBoCmRSv8TAOYvEQc_svBYo',
    appId: '1:197334825694:web:31534cd6b4a6afec85204f',
    messagingSenderId: '197334825694',
    projectId: 'diario-obra-1958a',
    authDomain: 'diario-obra-1958a.firebaseapp.com',
    storageBucket: 'diario-obra-1958a.appspot.com',
    measurementId: 'G-7HNYY2630N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ37rpQ6tmkqFH_lzwozsYn_fRe2pe8Sk',
    appId: '1:197334825694:android:263c760dfaa2944185204f',
    messagingSenderId: '197334825694',
    projectId: 'diario-obra-1958a',
    storageBucket: 'diario-obra-1958a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn_vZ9q1lOAg6evJLt8g9DR858j8FXtZc',
    appId: '1:197334825694:ios:267f2942ce65785e85204f',
    messagingSenderId: '197334825694',
    projectId: 'diario-obra-1958a',
    storageBucket: 'diario-obra-1958a.appspot.com',
    iosBundleId: 'com.example.diarioObra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn_vZ9q1lOAg6evJLt8g9DR858j8FXtZc',
    appId: '1:197334825694:ios:dca69a024e282eab85204f',
    messagingSenderId: '197334825694',
    projectId: 'diario-obra-1958a',
    storageBucket: 'diario-obra-1958a.appspot.com',
    iosBundleId: 'com.example.diarioObra.RunnerTests',
  );
}
